name: Publish

on:
  # publish from the Releases page:
  release:
    types: [published]
  # publish from the Actions page:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (e.g. 2.0.3)'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Build tools
      run: |
          python -m pip install --upgrade pip
          pip install build
    - name: Build
      run: |
          python -m build --wheel --sdist
    - name: Publish to Github
      uses: softprops/action-gh-release@v1
      with:
        files: 'dist/*'
        fail_on_unmatched_files: true
        tag_name: ${{ github.event.inputs.version }} # in the workflow_dispatch case, make a new tag from the given input; in the published release case, this will be empty and will fall back to updating that release.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        # TODO: Replace this personal API token with one that:
        #  - Points at pypi.org, not test.pypi.org
        #  - Is generated by the NeuroPoly PyPI account (https://github.com/neuropoly/onboarding/issues/140)
        password: ${{ secrets.TEST_PYPI_API_TOKEN_JOSHUACWNEWTON }}
        repository_url: https://test.pypi.org/legacy/
