name: Publish

on:
  # publish from the Releases page:
  release:
    types: [published]
  # test building only on PRs
  pull_request:

env:
  VERSION_NUMBER: ${{ github.event.release.tag_name }}

jobs:
  publish:
    name: Publish Package
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/setup-python@v3
           
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install build

    - name: Build
      run: python -m build --wheel --sdist

    - name: Publish to Github
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: 'dist/*'
        fail_on_unmatched_files: true
        tag_name: ${{ env.VERSION_NUMBER }}
        prerelease: ${{ contains(github.ref, 'rc') || contains(github.ref, 'dev') }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
    - name: Publish to PyPI
      if: startsWith(github.ref, 'refs/tags/')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        # TODO: Replace this personal API token with one that:
        #  - Points at pypi.org, not test.pypi.org
        #  - Is generated by the NeuroPoly PyPI account (https://github.com/neuropoly/onboarding/issues/140)
        password: ${{ secrets.TEST_PYPI_API_TOKEN_JOSHUACWNEWTON }}
        repository_url: https://test.pypi.org/legacy/
